name: "Integração  Api Enel com Home Assistant (Não oficial)"
description: "Addon para integrar no Home Assistant a api da rede de energia Enel"
version: "1.0.2"
slug: "modulo_enel"
init: false
discovery:
  - mqtt
services:
  - mqtt:need
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  40002/tcp: 40002
host_network: true
options:
  email: ""
  password: ""
  instalation: ""
  update_interval: 1
schema:
  email: str
  password: str
  instalation: "str?"
  update_interval: int
