name: "Integração  Api Enel com Home Assistant (Não oficial)"
description: "Addon para integrar no Home Assistant a api da rede de energia Enel"
version: "1.1.0"
slug: "modulo_enel"
init: false
discovery:
  - mqtt
services:
  - mqtt:need
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  40002/tcp: 40002
host_network: true
options:
  email: ""
  password: ""
  mqtt_host: ""
  mqtt_user: ""
  mqtt_password: ""
  instalation: ""
  temp_token: ""
  update_interval: 1
  debug: false
schema:
  email: str
  password: str
  mqtt_host: str
  mqtt_user: str
  mqtt_password: str
  instalation: "str?"
  temp_token: "str?"
  update_interval: int
