name: "Integração  Api Enel com Home Assistant (Não oficial)"
description: "Addon para integrar no Home Assistant a api da rede de energia Enel"
version: "1.0.0"
slug: "modulo_enel"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  40002/tcp: 40002
host_network: true
options:
  email: ""
  password: ""
  instalation: ""
  update_interval: 1000
  mqtt_host: "core-mosquitto"
  mqtt_user: ""
  mqtt_password: ""
  loglevel: "debug"
schema:
  email: str
  password: str
  instalation: "str?"
  update_interval: int
  mqtt_host: str
  mqtt_user: str
  mqtt_password: str
  loglevel: str

